[build]
target = "index.html"
dist = "../public/root"
release = false
filehash = false
public_url = "/"

[watch]
watch = ["src/", "index.html"]

[clean]
dist = "../public/root"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "[ ! -d \"./node_modules\" ] && npm i || :; npm run build" ]

[serve]
address = "127.0.0.1"
port = 8080
open = false
no_autoreload = false

