-- Add up migration script here

CREATE TABLE IF NOT EXISTS dynos (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    info_id INTEGER DEFAULT 1,
    uuid TEXT NOT NULL,
    data_checksum TEXT NOT NULL,
    verified BOOLEAN DEFAULT 0,
    start DATETIME NOT NULL,
    stop DATETIME NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
